### ISSUE TITLE
Не работают правки через "Источник"

### ISSUE THREAD

**Issue by vhar** [nakipelo/orchid-ckeditor#4]
Не сохраняются изменения сделанные через правки в режиме "Источник"

**Comment by EgorGruzdev** [comment]
Хочу уточнить, при переключение режима источник не сохраняет, если его не отключить, а если отключить режим, то все ок.

**Comment by vhar** [comment]
Переключаемся в режим "Источник", вносим изменения, сохраняем форму - изменения не сохранились.
Переключаемся в режим "Источник", вносим изменения, выходим из режима "Источник", сохраняем форму - все сохранилось.

**Comment by EgorGruzdev** [comment]
fix выгружен в версии 5.1.2

**Comment by EgorGruzdev** [comment]
fix выгружен в версии 5.1.2
